name: "Infra CLI Action"
description: "Install and run the infra CLI from the infra-new PyPI package"
author: "infra-new"

branding:
  icon: terminal
  color: blue

# Define your inputs here.
inputs:
  working-directory:
    description: "Working directory to run the command in"
    required: false
    default: "."
  github-repo:
    description: "GitHub repository to pass to the drift command (defaults to current repository)"
    required: false
    default: ""
  github-ref:
    description: "GitHub ref to pass to the drift command (defaults to current ref)"
    required: false
    default: ""
  api-key:
    description: "API key for the infra command"
    required: true
  plan-file-path:
    description: "Path to a json terraform plan. Can be create by running `terraform plan -out terraform.plan` followed by `terraform show -json > terraform-plan.json`"
    required: true
  github-access-token:
    description: "GitHub access token to pass to the drift command"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Get repository ID and commit hash
      id: get-repo-info
      shell: bash
      run: |
        REPO="${{ inputs.github-repo }}"
        if [ -z "$REPO" ]; then
          REPO="${{ github.repository }}"
        fi
        REF="${{ inputs.github-ref }}"
        if [ -z "$REF" ]; then
          REF="${{ github.ref }}"
        fi

        REPO_ID=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/$REPO" | jq -r '.id')
        echo "repo-id=$REPO_ID" >> $GITHUB_OUTPUT

        COMMIT_HASH=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/$REPO/commits/$REF" | jq -r '.sha')
        echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: Run infra command
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        REPO_ID="${{ steps.get-repo-info.outputs.repo-id }}"
        COMMIT_HASH="${{ steps.get-repo-info.outputs.commit-hash }}"
        ACCESS_TOKEN="${{ inputs.github-access-token }}"
        if [ -z "$ACCESS_TOKEN" ]; then
          ACCESS_TOKEN="${{ github.token }}"
        fi
        uvx --from infra-new infra drift --github-ref "$COMMIT_HASH" --github-repo-id "$REPO_ID" --api-key "${{ inputs.api-key }}" --plan-file-path "${{ inputs.plan-file-path }}" --github-access-token "$ACCESS_TOKEN"
