name: "Infra CLI Action"
description: "Install and run the infra CLI from the infra-new PyPI package"
author: "infra-new"

branding:
  icon: terminal
  color: blue

# Define your inputs here.
inputs:
  working-directory:
    description: "Working directory to run the command in"
    required: false
    default: "."
  github-repo:
    description: "GitHub repository to pass to the drift command (defaults to current repository)"
    required: false
    default: ""
  github-ref:
    description: "GitHub ref to pass to the drift command (defaults to current ref)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Run infra command
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        REPO="${{ inputs.github-repo }}"
        if [ -z "$REPO" ]; then
          REPO="${{ github.repository }}"
        fi
        REF="${{ inputs.github-ref }}"
        if [ -z "$REF" ]; then
          REF="${{ github.ref }}"
        fi
        uvx --from infra-new infra drift --github-repo "$REPO" --github-ref "$REF" ${{ inputs.command }}
