name: Release

on:
  release:
    types: [published]

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update major version tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          MAJOR_VERSION=$(echo $TAG | cut -d. -f1)
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION tag"
          git push origin $MAJOR_VERSION --force